version: "3.7"

services:
    tfserving:
        image: "yolov5s_serving"
        ports:
            - "8501:8501"
        networks:
            - proxynet

networks:
    proxynet:
        external:
            name: gymeqp_classifier

