version: "3.7"

services:
    rabbitmq:
        image: "rabbitmq:3.8.17"
        ports:
            - "5672:5672"
        volumes:
            - "rabbitmq_data:/data/rabbitmq"
        networks:
            - proxynet
         
    redis:
        image: "redis:alpine3.13"
        ports:
            - "6379:6379"
        volumes:
            - "redis_data:/data/redis"
        networks:
            - proxynet    
        
    celery:
        build:
            dockerfile: DockerfileCelery
            context: .
        depends_on:
            - rabbitmq
            - redis
            - fastapi
        environment:
            - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
            - CELERY_BACKEND_URL=redis://redis:6379/0
            - TFSERVING_URL=http://tfserving:8501/v1/models/rest_review_distilbert_base:predict
            - TOKENIZER_PATH=/data/token/msmarco-distilbert-base-v4
            - REST_DATA_PATH=/data/restaurant_data
        volumes:
            - "./celery_task:/celery_task"
        command: ["celery", "-A", "celery_task.tasks", "worker", "--loglevel=INFO"]
        networks:
            - proxynet

    fastapi:
        build:
            dockerfile: DockerfileFastapi
            context: .
        ports:
            - "8000:8000"
        depends_on:
            - rabbitmq
            - redis
        environment:
            - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
            - CELERY_BACKEND_URL=redis://redis:6379/0
            - TFSERVING_URL=http://tfserving:8501/v1/models/rest_review_distilbert_base:predict
        volumes:
            - "./app:/app"
        command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
        networks:
            - proxynet

    tfserving:
        image: "rest_review_distilbert_base"
        ports:
            - "8501:8501"
        networks:
            - proxynet

volumes:
    rabbitmq_data:
        driver: local
    redis_data:
        driver: local
        
networks:
    proxynet:
        name: restaurant_finder
